### ISSUE TITLE
コマンド送信をより確実に。

### ISSUE THREAD

**Issue by haniokasai** [itsu-dev/MiRmDockerClient#20]
docker top をparse

CMDに /minecraft/resourcesが含まれないかつ sshd を含まないプロセスがマイクラのプロセス。
この場合はpid 19193 を取得し、
```  
echo  "help" > /proc/19193/fd/0
```
とprocessbuilderでやる。

```
 docker top wwwwwwww_container
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                19118               19102               0                   13:04               ?                   00:00:00            /bin/sh -c sh /minecraft/resources/run-Main.sh
root                19147               19118               0                   13:04               ?                   00:00:00            sh /minecraft/resources/run-Main.sh
root                19169               19147               0                   13:04               ?                   00:00:00            /usr/sbin/sshd -D -e
root                19175               19147               0                   13:04               ?                   00:00:00            sh /minecraft/resources/run-BE-PMMP.sh
root                19193               19175               7                   13:04               ?                   00:00:00            PocketMine-MP 3.9.8+dev
[root@mirmtestenv docker-minecraft]# 

```

**Comment by haniokasai** [comment]
String dockercmd = "echo  \"" + cmd+ "\" > /proc/" + pid + "/fd/0";
            String result = processBuilt(new String[]{"/bin/sh", "-c", dockercmd});

としてあげればいいんだけど、osインジェクションができそう。

**Comment by haniokasai** [comment]
実際のところ、起動中にattachされるとコマンドが実行できない旨を送ったほうがよさそう

**Comment by itsu-dev** [comment]
ありがとう！
実際にlinuxで

>docker top test_container
...
root 1905 1902 1 Dec01 ? 00:16:53 PocketMine-MP 3.9.8+dev
...

>echo “say yes” > /proc/1905/fd/0
-bash: /proc/1905/fd/0: Text file busy

というような出力が得られて、サーバーにyesっていう文字は出なかった(=コマンドが実行されなかった？)んだけど、、

**Comment by haniokasai** [comment]
それはなぜだ、、、？
コンテナ作り直した？

**Comment by itsu-dev** [comment]
もしかして作り直す必要があった？

**Comment by haniokasai** [comment]
うん

**Comment by haniokasai** [comment]
それとdocker minecraftのバージョンが違うかもしれないよ

**Comment by itsu-dev** [comment]
できた、ありがとう

**Comment by haniokasai** [comment]
よし！😸

**Comment by itsu-dev** [comment]
https://github.com/itsu-dev/MiRmDockerClient/commit/f75a6ffc5395c99aba1f4e2d789a3c644a93563b

https://github.com/itsu-dev/MiRmDockerClient/commit/e77da01d87a855bdde2e520eecfd4d8d7725f43b
