### ISSUE TITLE
Dockerコンテナ内だとprocにアクセスできない（解決

### ISSUE THREAD

**Issue by haniokasai** [itsu-dev/MiRmDockerClient#21]
ls: cannot access '/newproc/14227/fd/0': No such file or directory
[root@mirmtestenv sys]# docker exec mirm_smx /bin/bash -c "echo \"help\" > /newproc/14227/fd/0"
/bin/bash: /newproc/14227/fd/0: Permission denied
[root@mirmtestenv sys]# docker exec mirm_smx /bin/bash -c "echo \"help\" > /newproc/14227/fd/0"
/bin/bash: /newproc/14227/fd/0: Permission denied
[root@mirmtestenv sys]# docker rm -f mirm_smx
mirm_smx
[root@mirmtestenv sys]# docker create --name mirm_smx --memory=500mb --network="host" -e DOCKER_HOST=/var/run/docker.sock -v /var/run/:/var/run/ -v /smx/sys:/smx/sys -v /smx/backupfiles:/smx/backupfiles --cap-add SYS_PTRACE -v /proc:/newproc:ro haniokasai/docker-smx:latest
f24d42848e4ecc589fc407e8fd8e9f00ff3e228604362a70a157647618262b91
[root@mirmtestenv sys]# docker restart mirm_smx
mirm_smx
[root@mirmtestenv sys]# docker exec mirm_smx /bin/bash -c "echo \"help\" > /newproc/14227/fd/0"
[root@mirmtestenv sys]#

**Comment by itsu-dev** [comment]
ないす！！！
